#!/bin/bash

if [ ! -e $HOME/.config/nvim ] ; then 
	git clone https://github.com/tulilirockz/tulili.nvim $HOME/.config/nvim
fi

if ! command -v just ; then
	curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to "$HOME/.local/bin"
fi

