#!/bin/bash

function set_fish_stuff {
	chsh -s /usr/bin/fish
	curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
	fish -c 'omf install chain'
}

if command -v fish ; then
	set_fish_stuff
fi
